### ISSUE TITLE
Value binding not updating when clicking outside the document in Chrome/WebKit

### ISSUE THREAD

**Issue by sebmartin** [knockout/knockout#764] opened 2012-12-14 15:12 UTC
There appears to be an issue in Chrome and Safari where changing the value in an input field does not update the observable if the user clicks outside of the HTML document.

Confirmed as bug in the following browsers with KO 2.2.0:
- Chrome for MacOS Version 23.0.1271.97
- Chrome for Windows Version 23.0.1271.97
- Safari for MacOS Version 6.0.2 (8536.26.17)

To reproduce:
- go to http://jsfiddle.net/rBGFX/3/
- change text in the input field
- click on the browser's address bar or any other window/application

Expected behavior:
- the label (p element) is updated with the new value

Actual behavior:
- the label is unchanged (still reads "test")

Note that the behavior is as expected in FireFox and IE 9.

**Comment by SteveSanderson** [comment] 2015-04-07 13:43
Thanks for discussing this. Since @jrsearles notes this works as intended in current browsers, and the `textInput` binding is another alternative now, I'll close this. But please reopen if you think there's still an issue.

**Closed by SteveSanderson** 2015-04-07 13:43 UTC
Labels: close, type: bug
