### ISSUE TITLE
Documentation request: use anchor links for easy share

### ISSUE THREAD

**Issue by alvarotrigo** [knockout/knockout#1817] opened 2015-06-24 10:20 UTC
It would come in handy to be able to click on the documentation headers inside each section and get redirected to its anchor link (#haderTitle)

This way sharing chunks of documentation with other people (on stackoverflow, github, freenode chat..etc) would be much easier and precise. 

It is quite a typical approach for APIs docs and Frameworks cookbooks, for example:

http://expressjs.com/4x/api.html#app.engine
https://nodejs.org/api/stream.html#stream_readable_setencoding_encoding
http://book.cakephp.org/2.0/en/controllers.html#controller-actions
http://laravel.com/docs/5.1#configuration

Just making live easier :)

**Comment by mbest** [comment] 2015-06-24 10:45
Duplicate of #1763.

**Closed by mbest** 2015-06-24 10:45 UTC
