### ISSUE TITLE
Mobile Network Compression & Virtual Elements / Container-Less Control Structures

### ISSUE THREAD

**Issue by JD-Robbs** [knockout/knockout#1832] opened 2015-07-23 09:21 UTC
Some time ago, I came across an issue where my mobile network provider would strip-out HTML comments to save on bandwidth. Obviously, this can cause havoc regarding the container-less control structures.

In my case, on EE in the UK, this could be alleviated by simply moving the affected code into templates but I am aware that you can't count on other providers not muddling with script-tags or requested templates, too.

While this is probably a super minority problem, I wonder if there is any value in something like the following (pseudo!) syntax:

    <ul>
    <ko data-bind="foreach: items">
       <li data-bind="text: title"></li>
    </ko>
    </ul>

Or similar, although I think this just causes headaches with the rendering process as the `<ko />` tags would need to be removed, etc. I know it's sad that I'm even putting it out there. :laughing: 

Anyway, maybe you solved it differently? Or someone knows for sure that script-tags or requested templates won't ever be compressed?

**Comment by brianmhunt** [comment] 2015-07-23 10:39
@JD-Robbs What about the moustache syntax (`{{# foreach ...}}`)  of [knockout punches](http://mbest.github.io/knockout.punches/)?

**Comment by simonmurdock** [comment] 2015-07-23 11:10
This would also break a bunch of in-line browser specific CSS rules. Ridiculous that they are stripping that kinda stuff out.

**Comment by JD-Robbs** [comment] 2015-07-23 12:45
@simonmurdock Yes, that's why I hesitated even mentioning this pseudo example. I merely meant to highlight that this sort of unacceptable muddling with code by mobile networks is happening and causing grief. Especially when you're on an essentially unlimited data plan. :laughing: 

@brianmhunt I didn't even think of that! No,this shouldn't be stripped-out. What the networks are doing is simply applying a set of compression rules that they *think* does not cause functional problems - whitespace, CSS compression and concatenation, JS compression and concatenation (super-basic compression excluding changing property names and so on) and, above all, stripping-out any and all HTML comments.

Anyway, thanks for the pointer - I will definitely look into using moustache should my current workarounds stop, well, working.

**Comment by brianmhunt** [comment] 2015-07-23 13:17
@JD-Robbs Is it fair to say that the issue is outside the control of Knockout, or alternatively the best solution KO could provide is something like KO.punches?

You might also want to check to see if there's a flag you can put in your HTML that'll prevent it from being "compressed".

I'll close this on the basis that there's not much we at KO can do here, but if I'm missing something please let me know and we can reopen– and of course happy to keep the discussion going here even if the issue is marked as closed.

Cheers

**Closed by brianmhunt** 2015-07-23 13:17 UTC
