### ISSUE TITLE
After changing value of observable array on key press the bindings in the row with focused input stop working

### ISSUE THREAD

**Issue by NeuwirthD** [knockout/knockout#1914] opened 2015-10-22 13:55 UTC
We have a list of editable items. If we "save" this list after pressing enter key the bindings in the row with focused input stop working. This happens only in IE and Edge.

Example: http://jsfiddle.net/010as5f8/

Steps to reproduce:
Click in the input with the "Value1" text.
Press enter. (The value of observable array is changed)
Click on the button in the row with "Saved1" value → nothing happens.

When you click on the buttons below the button in the first row starts working again.

If we blur the input before changing the value of observable array everything works fine. (line 49)

Is there another workaround except for blurring the input?

**Comment by mbest** [comment] 2015-10-22 20:08
You could also update the value in the sub-viewmodel instead of the whole viewmodel. http://jsfiddle.net/010as5f8/4/

**Comment by mbest** [comment] 2015-10-22 20:11
If you need to create a new viewmodel for each item, you can wrap each one in an observable and just update each observable. http://jsfiddle.net/010as5f8/5/

I updated the Knockout version in the fiddle to 3.3.0.

**Comment by NeuwirthD** [comment] 2015-10-23 06:49
Thank you for the reply. Yes, that works for this simplified sample. In reality our models are much more complex.

I'll have to find the solution inside the saveOnEnter function. In fact we have a general command object invoking a function passed to the command. I could blur the input and after the function is invoked I would focus the input again but the function often runs asynchronous code especially for loading and saving models. So the command doesn't know when the function finishes.

**Comment by mbest** [comment] 2015-10-23 09:07
Another option is to use the [Knockout Repeat](https://github.com/mbest/knockout-repeat) binding instead of `foreach`. I've updated your example to use `repeat`: http://jsfiddle.net/010as5f8/6/ (Note that the example also sets `ko.bindingHandlers.repeat.itemName = '$data';` which makes `repeat` use `$data` instead of `$item`.)

**Comment by mbest** [comment] 2015-10-23 09:08
I'm not sure how Knockout can specifically work around the original problem, which appears to be a bug in IE and Edge.

**Comment by NeuwirthD** [comment] 2015-10-23 13:53
Ok, thank you.

**Comment by brianmhunt** [comment] 2015-10-23 14:45
Closing this on the basis that the problem is with Edge and not KO – though any suggestions on workarounds are most welcome!  Of course, please feel free to reopen if I've misunderstood or there's something that can be done in KO to solve this.

**Closed by brianmhunt** 2015-10-23 14:45 UTC
