### ISSUE TITLE
`pureComputed` sometimes doesn't pick up a change in a dependency

### ISSUE THREAD

**Issue by m-lieshout-adi** [knockout/knockout#1992] opened 2016-02-02 01:55 UTC
**Setup**

1. Have two `pureComputed` observables, one of which depends on the other.
2. Have these two observables bound to the view.
3. Remove the part of the view they are connected through (using an if binding for instance), putting the computed observables to sleep.
4. While they are asleep, modify a dependency of them that will result in a new value when they next recalculate.
5. Wake up the computed observables, starting with the computed that is depended on by the other one first.

**Expected behaviour**
When the second computed wakes up, it will detect that the first computed has a modified value and thus will recalculate.

**Actual behaviour**
The second computed does not update.

**Analysis**
The second computed thinks that none of its dependencies have updated since it fell asleep, and has not been marked as stale so does not rerun its read function.

Debugging this it looks like it may be some sort of edge case related to the version of the value in the first computed. The version was not changed after it updated when it woke up, so the second observable seems to think that it hasn't changed.

**Example**
Here is a jsfiddle link demonstrating this bug in action. I would expect every time the two numbers appear in my example that they would have the same value, but instead the second one never updates.
[jsfiddle](http://jsfiddle.net/m_lieshout_adi/L45jygsz/1/)

The order of the elements that the `pureComputed` observables are bound to is crucial to reproducing this bug. If you reverse the two divs in the [jsfiddle](http://jsfiddle.net/m_lieshout_adi/L45jygsz/1/) then the values update correctly.

**Comment by brianmhunt** [comment] 2016-02-02 02:59
Great report, thanks @m-lieshout-adi .

I'm guessing the issue is here: https://github.com/knockout/knockout/blob/master/src/subscribables/dependentObservable.js#L370-L416

**Comment by IanYates** [comment] 2016-02-02 03:29
I think this is the same as #1975 

I say that because it
* it sounds similar :)
* I have taken the patch made by @mbest and applied it to my local copy of knockout-3.4.0.debug.js.  If I reference my copy in the fiddle then I don't see the bug.

Reading through the change in [eb88065](https://github.com/knockout/knockout/commit/eb880656a8daf698d4fd56e15f2f82ba89ca1d9d) it seems to fit.

**Comment by IanYates** [comment] 2016-02-02 03:32
I do like the reproduction expressed in this issue - it was a very clear example :)

**Comment by jeremyVignelles** [comment] 2016-02-10 14:19
Hi,
Is there a planned date for the 3.4.1 release?
I came across the same issue again, and I didn't find a way to easily integrate the patch in my project (I'm using bower).

**Comment by brianmhunt** [comment] 2016-02-10 17:28
@knockout/owners  Are we able to run a 3.4.1 that resolves this?  There haven't been many patches since 3.4, but this one in particular strikes me as a fairly concerning problem.

**Comment by mbest** [comment] 2016-02-10 21:36
I'm okay with a 3.4.1 release that includes this patch. @brianmhunt Would you like me to take care of it?

**Comment by IanYates** [comment] 2016-02-11 00:30
There are a couple of patches from the current version in the repo that I've brought into my KO code, but to do so I'm running the debug version since I don't have all of the KO build tools on my machine.

* This patch.
* A patch to the 'trackArrayChanges' extender.

Could they both be included?

I've also brought in the extra class/css binding handler alias but I suspect this will have to wait for 3.5 since it's not really a bug fix

**Comment by brianmhunt** [comment] 2016-02-11 01:22
@mbest that'd be fantastic if you could, thank you.

I'm ok with the changes @IanYates suggested (and anything merged since 3.4.0), provided of course there's adequate testing and it's not too much trouble.

**Comment by mbest** [comment] 2016-02-11 01:34
According to http://semver.org/, we can't include anything that adds to the API (like the new bindings) in a patch version; we can only included bug fixes. So that includes #1974, #1975, and #1415.

**Comment by brianmhunt** [comment] 2016-02-11 01:57
Got it, thanks @mbest.  That works for me.

**Comment by IanYates** [comment] 2016-02-11 02:16
:+1:

**Comment by mbest** [comment] 2016-02-11 22:29
I've created #2001 for further discussion and planning regarding 3.4.1.

**Closed by mbest** 2016-02-11 22:29 UTC
Labels: type: meta
