### ISSUE TITLE
Wish Knockout to release a jQuery-dependent version

### ISSUE THREAD

**Issue by infinnie** [knockout/knockout#1729] opened 2015-03-16 12:20 UTC
—A release some lighter in weight, intended for those who would anyway depend on jQuery.

**Comment by brianmhunt** [comment] 2015-03-16 13:09
@infinnie Thanks for the report, I had the same thoughts a while back. This seems to be a duplicate of #1001, and I will close it on that basis, with a quote from Steve Sanderson that may illuminate the status of this direction:

> Indeed, KO is independent of jQuery. Making KO depend on jQuery would theoretically permit a slightly smaller build, but the difference is unlikely to be big enough to greatly benefit anyone, and the loss of framework independence and IE6-8 support would be a high price to pay for that.

> Thanks for suggesting this. Personally this isn't a direction I'm keen on pushing, but if a lot of people in the community were enthusiastic that we should do it, then we could review that in the future. Hope that's OK!

If you think there is something more or different that could be done here (i.e. you think I am closing this in error), please let me know though.

Cheers

**Closed by brianmhunt** 2015-03-16 13:09 UTC

**Comment by infinnie** [comment] 2015-03-16 13:33
And IE 6-8 support is built in jQuery 1.x, and dropped in jQuery 2.x
