### ISSUE TITLE
Cannot extend ko.applyBindings

### ISSUE THREAD

**Issue by nthsense** [knockout/knockout#917] opened 2013-04-10 14:58 UTC
We're trying to extend ko.applyBindings in knockback (see https://github.com/kmalakoff/knockback/issues/63) but running into issues when using the minified version of knockout.  We extend using this general pattern:

```var applyBindings = ko.applyBindings;
ko.applyBindings = function(){
 // do knockback stuff here
applyBindings.apply(this,arguments);
}```

This works out fine when running kockout.debug, but the minified version is still internally referencing the original version of the function.  Can you suggest an alternative means of extending the function, or restructure knockout to permit extension?

**Comment by SteveSanderson** [comment] 2015-04-07 13:16
Well, it's a year later, so closing as by design :)

At some point, this design may change if we stop using Closure Compiler name mangling.

**Closed by SteveSanderson** 2015-04-07 13:16 UTC
Labels: close
