### ISSUE TITLE
Breaking change 3.5.0 -> 3.5.1 - change event is fired before select 'value' observable is updated

### ISSUE THREAD

**Issue by flmbray** [knockout/knockout#2558] opened 2021-01-13 06:44 UTC
In version 3.5.0, when a change event was applied to a select dropdown (and maybe other items, I haven't tried), the method would fire **_after_** the observable was updated.  In other words, accessing the observable from the change method would provide the **_new_** value.  

In version 3.5.1, this appears to have changed, and the the method now fires **_before_** the observable gets updated, such that accessing the observable from the change method provides the **_old_** value. 

**JSFiddle Demo:** [https://jsfiddle.net/flmbray/g3jem65c/](https://jsfiddle.net/flmbray/g3jem65c/)

**Comment by mbest** [comment] 2021-02-28 01:14
I think this is a duplicate of #2530, which I've already added a fix for (but not yet released).

**Closed by mbest** 2021-02-28 01:14 UTC
