### ISSUE TITLE
Knockout cannot process component template correctly if it is loaded by element identifier (IE 11).

### ISSUE THREAD

**Issue by maxim-boligatov** [knockout/knockout#1836] opened 2015-07-30 01:37 UTC
The following code works fine in Firefox, Chrome, Opera, but does not work in IE (at least in IE 11):

```html
<template id="common-account">
  <p>First name: <input data-bind="value: firstName" /></p>
  <p>Last name: <input data-bind="value: lastName" /></p>
  <h2>Hello, <span data-bind="text: fullName"> </span>!</h2>
</template>
```
```js
var ViewModel = function(first, last) {
    this.firstName = ko.observable(first);
    this.lastName = ko.observable(last);
 
    this.fullName = ko.pureComputed(function() {
        return this.firstName() + " " + this.lastName();
    }, this);
};

ko.components.register("common-account", {
    template: { element: "common-account" },
    viewModel: {
        createViewModel: function (params, componentInfo) {
            var viewModel = new ViewModel("User", "Test");
            
            return viewModel;
        }
    },
    synchronous: true
});

ko.applyBindings();

```

<common-account></common-account>

To explain solution I have created jsfiddle: http://jsfiddle.net/qp49uz0v/16/
It raises exception that firstName is undefined.

IE works fine as well only if template is specified as string (like it is here: http://jsfiddle.net/47e2gpqq/4/).

**Comment by IanYates** [comment] 2015-07-30 07:56
Interesting problem.  I can confirm it happens for me too (IE 11 on Windows 8.1)
I also loaded up a copy of Win 10 and tried it in Edge.  Same issue.

@brianmhunt  - I wonder if this is what's causing grief for the new KO docs site in IE?  I recall reading this morning in your blog post that you concatenate all of the templates into a single file.  Presumably they're referenced by their id in a manner similar to that described in this issue.

**Comment by brianmhunt** [comment] 2015-07-30 12:53
@IanYates Ahh yes, that may indeed be the issue.

@maxim-boligatov Does the problem exhibit in IE when you rewrite the `<template id='..'></template>` as a `<script id='...' type='text/x-ko`></script>`? Older WebKit may need this rewrite too.

If that does work, then one can do a [javascript polyfill for the `<template>` tag](https://github.com/neovov/template-element-polyfill) or a [relatively simple jQuery equivalent](http://stackoverflow.com/questions/8584098).

**Comment by IanYates** [comment] 2015-07-30 13:24
@brianmhunt  - just tried script tags.  They work a treat - http://jsfiddle.net/qp49uz0v/18/  :)

**Comment by brianmhunt** [comment] 2015-07-30 13:42
Thanks @IanYates ; looks like `<template>` is not supported in any version of IE, per http://caniuse.com/#feat=template

So it looks like this is not a Knockout issue *per se*, but an IE problem. We all have to fall back on a polyfill for IE support.

This being an IE issue I'm not sure what we could be doing better in KO here.  @maxim-boligatov if you think there's still something KO could be doing better here please let me know. In the mean time I'll close this.  Thanks and cheers.

**Comment by maxim-boligatov** [comment] 2015-07-30 16:37
@brianmhunt Yes I think knockout can fix it easy.. maybe some trick for IE. At least the following code work fine:

```js
var ViewModel = function(first, last) {
    this.firstName = ko.observable(first);
    this.lastName = ko.observable(last);
 
    this.fullName = ko.pureComputed(function() {
        return this.firstName() + " " + this.lastName();
    }, this);
};

var trick = document.getElementById('common-account');

ko.components.register("common-account", {
    template: trick.innerHTML,
    viewModel: {
        createViewModel: function (params, componentInfo) {
            var viewModel = new ViewModel("User", "Trick");
            
            return viewModel;
        }
    },
    synchronous: true
});

ko.applyBindings();
```
http://jsfiddle.net/qp49uz0v/20/

P.S. Templates are proposed in official knockout documentation. Since knockout supports IE I guessed that it will support "template" everywhere.

P.S.S. Regarding new site... In my personal opinion current version of site is more interesting than new one... from point of view of design ;) Current - cheerful but professional, new one - more simple (it is good) but to much mannered...

**Comment by maxim-boligatov** [comment] 2015-07-30 17:24
I have posted previous comment too early. So I wrote new one.
Idea is the same bind template as string. So new jsfiddle url: http://jsfiddle.net/qp49uz0v/26/
I think knockout can easy detect all templates if it is IE, cache inner html and drop element itself.

```html
<template id="common-account">
  <p>First name: <input data-bind="value: firstName" /></p>
  <p>Last name: <input data-bind="value: lastName" /></p>
  <h2>Hello, <span data-bind="text: fullName"> </span>!</h2>
</template>

<common-account></common-account>
```

```js
var ViewModel = function(first, last) {
    this.firstName = ko.observable(first);
    this.lastName = ko.observable(last);
 
    this.fullName = ko.pureComputed(function() {
        return this.firstName() + " " + this.lastName();
    }, this);
};

var trick = document.getElementById('common-account');
var template = trick.innerHTML;
trick.parentNode.removeChild(trick);

ko.components.register("common-account", {
    template: template,
    viewModel: {
        createViewModel: function (params, componentInfo) {
            var viewModel = new ViewModel("User", "Trick");
            
            return viewModel;
        }
    },
    synchronous: true
});

ko.applyBindings();
```

**Comment by brianmhunt** [comment] 2015-07-30 17:41
Thanks @maxim-boligatov & @IanYates – I think I see this now. Sorry, it takes me a minute. :grin:

I am guessing that at [components/defaultLoader.js#L168-L170](https://github.com/knockout/knockout/blob/master/src/components/defaultLoader.js#L168-L170) we'd want something like:

```javascript
                if (isDocumentFragment(elemInstance.content)) {
                    return ko.utils.cloneNodes(elemInstance.content.childNodes);
                }
                //  Fallback where <template> tag is not natively supported. See #1836.
                return ko.utils.parseHtmlFragment(elemInstance.innerHTML);
```

@mbest Is the potential patch here this simple?

**Comment by mbest** [comment] 2015-07-30 19:45
@brianmhunt, I'll take a look.

**Comment by brianmhunt** [comment] 2015-07-31 14:42
@maxim-boligatov @IanYates What does the [following](https://github.com/knockout/knockout/blob/master/src/components/defaultLoader.js#L186-L193) yield on IE?

```javascript
    function isDocumentFragment(obj) {
        if (window['DocumentFragment']) {
            return obj instanceof DocumentFragment;
        } else {
            return obj && obj.nodeType === 11;
        }
    }
```

where `obj` is the `document.getElementById('common-account')`?

**Comment by chessels** [comment] 2015-08-04 10:17
This is already fixed. See [issue 1783](https://github.com/knockout/knockout/issues/1783).

**Comment by mbest** [comment] 2015-08-04 10:21
Thanks @chessels for reminding us. We need to get 3.4.0 out the door!

**Closed by mbest** 2015-08-04 10:21 UTC
Labels: affected: average, severity: minor, type: bug
