### ISSUE TITLE
cloneNodes in IE<9

### ISSUE THREAD

**Issue by frankabbruzzese** [knockout/knockout#1752] opened 2015-04-07 18:25 UTC
The native template engines has a check to avoid the usage of cloneNode in IE<9, while components uses ko.utils.cloneNodes that in turn uses browser native cloneNode.
Either the first test is unnecessary and and slower down template engine by transforming templates into text instead of cloning them, or components dont work properly with IE<9....
I have no IE<9 browser so I can't check, but someone should verify this, and fix properly one of the two pieces of code

**Comment by SteveSanderson** [comment] 2015-04-08 11:47
Thanks for reporting this. I think it's a duplicate of #1636, so I'll close this in favour of that one, but please reopen if you don't think this is a duplicate!

**Closed by SteveSanderson** 2015-04-08 11:47 UTC
