### ISSUE TITLE
in 3.5.0 with deferUpdates enabled , a problem with "if" binding and child component which recursively embeds self

### ISSUE THREAD

**Issue by eapearson** [knockout/knockout#2414] opened 2018-09-17 16:50 UTC
I had noticed some odd performance issues using a recursive component (it builds a tree) which is switched on and off using an "if" binding, while using the new 3.5.0 builds.

After some time debugging, I determined that it was triggered by setting deferUpdates to true. I've been running with deferUpdates enabled for quite some time without any problems.

The recursive component builds up fine, but when removing the top level component by setting the value bound to the "if" binding to false, the browser will pause or even hang. The precise behavior depends on the depth of recursion. With the demo linked below, at a recursion depth of about 15 the performance lag is noticeable, at 20 or higher the browser will start to complain about a slow script, and by 30 the browser will effectively hang.

This behavior is exhibited on on 3.5.0, beta through rc2, with deferUpdates enabled. It is not exhibited in 3.4.2.

I have been using 3.5.0 since the beta with no problems other than this.

I have set up some jsfiddles to demonstrate this. The examples are much simplified and contain none of the code which originally tripped the issue for me:

With 3.5.0-rc2 demonstrating the issue:
https://jsfiddle.net/eapearson/vdkn7ftj/25/

And 3.4.2 in which the issue is not present:
https://jsfiddle.net/eapearson/vdkn7ftj/25/

I have tracked the problem down to this commit:

https://github.com/knockout/knockout/commit/5dc0ba0a8a9b8f90bcf9a68b84ed914754951ada

That is, knockout built with this commit exhibits the problem, with prior commits does not.

I had attempted to replicate the issue by manually nesting 20 identical components - so emulating the depth of component embedding but without recursion - and the issue was not exhibited.

**Comment by mbest** [comment] 2018-09-19 17:29
Thanks for the detailed information.

**Comment by mbest** [comment] 2018-09-19 17:47
Thanks for the detailed information. However, the 3.4.2 example is the same link as the 3.5.0 example.
--

**Comment by mbest** [comment] 2018-09-19 18:28
The issue appears to come from the deeply nested `if` or `ifnot` bindings. I am also able to prevent the problem by changing the binding in the component from `ifnot: depth === 0` to `template: {if: depth}`. I will continue to investigate.

**Comment by eapearson** [comment] 2018-09-19 19:08
Sorry about the copy-pasta error, that 3.4.2 example should be https://jsfiddle.net/eapearson/t5phov78/

**Comment by mbest** [comment] 2018-09-20 18:19
The change in #2234 is the culprit. It creates a dependency on the `if` condition for all descendant bindings, which isn't such a big deal if there are no nested `if` bindings as well, With each level of nesting, though, the number of operations is doubled or O(n^2).

Rather then trying to fix the update algorithm, I think I might just make the behavior from #2234 optional, since it's only needed in very specific cases.

**Comment by eapearson** [comment] 2018-09-20 20:35
Thanks for looking into it; Interesting; I've been working with a local build of knockout which removes that dependency in the if binding's child context or just uses the current binding context, but wasn't sure whether I had stumbled onto something which just happened to work, or what deleterious effects that change would have (none so far for me). I did see there was an issue which inspired this change, but didn't have time to investigate further (I'm the only knockout user at work, and don't want to rock the boat with excessive debugging time!)

**Comment by fastfasterfastest** [comment] 2018-09-22 00:33
> Rather then trying to fix the update algorithm, I think I might just make the behavior from #2234 optional, since it's only needed in very specific cases.

I think making the behavior from #2234 optional might not be a good idea.

I think the issue described in #2234 (which was initially discussed in #2226) is a bug, and as such should be fixed.  I don't think that issue is a "very specific case" - #2226 and #2234 contain examples, samples and scenarios that I imagine are quite common.

#2226 also has discussions about various approaches to implementing a fix - perhaps one of those will also avoid the issue described here.

(If anything, perhaps recursively invoking a knockout template hundreds or thousands of times is the "specific case", and if there is a work-around or pattern to avoid performance issues in such cases perhaps that would be a better approach.  Obviously, it would be better to have/find an implementation that avoids such issues altogether.)

**Comment by mbest** [comment] 2018-09-22 08:07
@fastfasterfastest Thanks for your input. I also came to a similar conclusion and have been working on improving the algorithm for reordering binding updates. I'm leaning toward a system that specifically reorders the updates based on some sort of binding order index.

**Comment by chrisknoll** [comment] 2018-09-22 15:41
Ordering binding updates is a great idea.  I imagine an efficient approach might be to structure the updates in a tree structure, such that descendants of a node in a tree (representing  the child dependencies for updates) you can quickly determine which elements in the dom you don't need to re-evaluate due to some higher level dom element disposal.  I'm thinking specifically on dom-level updates because a child dom element can only exist in at most one parent (same with a binding, i suppose).  I say this because I wouldn't make a tree of observable-dependencies, because I believe you would have a case where a dependent observable may appear across different nodes in a tree (ie: one observable can be observed by multiple parent observables).

Anyway, sorry for the ramblings, just wanted to chime in that it is very encouraging to hear about optimizations.

**Comment by fastfasterfastest** [comment] 2018-09-22 18:07
It's been a while now so I don't remember the details right off the bat... but I think the implementations suggested for issue #2226/#2234 handled the top-down ordering automatically, e.g. see https://github.com/knockout/knockout/pull/2226#issuecomment-297829323

>In terms of time, I am not sure - although the descendant bindings may have a dependency on their ancestor bindings, the above changes mostly/only(?) cause the ancestor binding to be scheduled to be evaluated before the descendant bindings, right? And when they (the ancestor bindings) do change, they will actually delete the descendants - so there may even be an improvement from a time performance point of view, since now the change would be propagated top-down and all the descendants would be vaporized before being notified.
...
even though the descendant bindings have a dependency and would get notified, the fact that the ancestor binding gets evaluated first, and while doings so it deletes the descendants, the descendant bindings would actually not get notified.

**Comment by mbest** [comment] 2018-09-25 18:46
#2234 was a solution to the out of order updates that works both with and without deferred updates. But while thinking about this again, I'm comfortable with a solution that only support deferred updates. That allows us to easily deal with binding updates separately from observable updates.

I've worked on a solution that does just that. You can see the code here: https://github.com/knockout/knockout/compare/2414-reordered-binding-updates I'd like to get a better sense for how real-world applications behave with this system and so have included some statistics calculations into it. I hope you guys can try it and report your results. I've built the debug version of the code here: http://bestware.us/knockout/2414-binding-updates/knockout-latest.debug.js After running your application with it, check the values in `window.scheduled`.

**Comment by eapearson** [comment] 2018-09-25 22:18
wow, thanks @mbest! Trying it out now, so far so good, including the actual code which triggered this behavior for me. I'll use it in the app I'm currently developing and report any issues.

What would be interesting to report from window.scheduled? Here is its state after about a minute spent exercising the recursive component (which works great now):

cleaned: 0
cleanup: 202
initial: 202
ordered: 930
rescheduled: 591
unordered: 75

**Comment by mbest** [comment] 2018-09-26 03:51
Thanks @eapearson. That's great information. One assumption I want to test is whether `cleaned` is ever non-zero. I'm also curious about the ratios between the others.

**Comment by mbest** [comment] 2018-10-04 08:09
@fastfasterfastest @chrisknoll What are your thoughts?

**Comment by chrisknoll** [comment] 2018-10-04 15:57
So, I grabbed the debug and went to one of our pages that uses a custom databind for datatabels.net, and got this error in console:

```
                // It's an anonymous template - store the element contents, then clear the element
                var templateNodes = ko.virtualElements.childNodes(element);
                if (templateNodes.length > 0) {
                    var container = ko.utils.moveCleanedNodesToContainerElement(templateNodes); // This also removes the nodes from their current parent
                    new ko.templateSources.anonymousTemplate(element)['nodes'](container);
                } else {
                    throw new Error("Anonymous template defined, but no template content was provided");
                }
```

The stacktrace of the binding led through here: (this is our custom binding, which handles ```<thead>``` content if found in the set of nodes.
```
				// For case of complex header which uses data-bindings (https://datatables.net/examples/advanced_init/complex_header.html)
				if ($(element).find('thead')[0]) {
					ko.applyBindings(bindingContext, $(element).find('thead')[0]);
				}
```

The component's HTML block looks like this:

```
<table width="100%" class="conceptTable stripe compact hover" cellspacing="0" cellspacing="0" data-bind="dataTable:{
			data: $component.tableData,
			options: {
				dom: $component.dom,
				colVis: $component.colVis,
				language: $component.language,
				buttons: $component.buttons,
				rowCallback: $component.rowCallback,
				lengthMenu: $component.lengthMenu,
				orderClasses: $component.orderClasses,
				ordering: $component.ordering,
				order: $component.order,
				columns: $component.columns,
				autoWidth: $component.autoWidth,
				deferRender: $component.deferRender,
				pageLength: $component.pageLength,
				drawCallback: $component.drawCallback
			},
			scrollOptions: $component.scrollOptions,
			onRowClick: $component.rowClick
	} ">
		<thead data-bind="template: { name: $component.headersTemplateId }"></thead>
</table>
```

So, in 3.3 and 3.4 (I've tried both) this apply binding does not fail (I'm not sure what it projects when you don't set the value of $component.headersTempalteId), but 3.5 doesn't allow this.

I'm going to alter my own code to check for the presence of a 'headersTemplateId' in the component of the datatable binding before calling applyBindings and see if that helps.

But, I am just posting the error here so you know I'm looking through it, and also that this may be a regression of some kind.

**Comment by chrisknoll** [comment] 2018-10-04 16:04
Update:  adding this:
```
if (bindingContext.$component.headersTemplateId && $(element).find('thead')[0]) {
	ko.applyBindings(bindingContext, $(element).find('thead')[0]);
}
```
Bypasses the applyBindings and allows the component to load.  So, problem soved on my side, but still possible backward-compatibility issue in 3.5 related to template names not being found.  Maybe in prior versions it was ignored?

**Comment by chrisknoll** [comment] 2018-10-04 16:18
Ok, my results after breezing through my app:
Without deferred udpates (I figure I would test this mode)
```
cleaned: 0
cleanup: 0
initial: 0
ordered: 0
rescheduled: 0
unordered: 0
```
with deferred updates:

```
cleaned: 0
cleanup: 184
initial: 184
ordered: 415
rescheduled: 428
unordered: 243
```

So, i went a little deeper into the app with deferred udpates enabled to check on the more observable-dependent behavior, but those are the results i got. I'm not sure under what context the cleaned value would be > 0, but it was 0 for me as well, and I went through many pages that create and dispose components/view models.

**Comment by mbest** [comment] 2018-10-04 18:42
> Bypasses the applyBindings and allows the component to load. So, problem soved on my side, but still possible backward-compatibility issue in 3.5 related to template names not being found. Maybe in prior versions it was ignored?

I'll look into this. Thanks for the feedback. 

> So, i went a little deeper into the app with deferred udpates enabled to check on the more observable-dependent behavior, but those are the results i got. I'm not sure under what context the cleaned value would be > 0, but it was 0 for me as well, and I went through many pages that create and dispose components/view models.

This helps me feel confident that I don't need to bother with a "cleanup" task. It's also good to see that more updates are already ordered than not.

**Comment by fastfasterfastest** [comment] 2018-10-04 22:15
> What are your thoughts?

I don't know...

Intuitively it feels like this should be able to be handled by carefully creating observable dependencies without a need for a special and separate "binding order mechanism" involving scheduling etc. which adds complexity to the system.

In https://github.com/knockout/knockout/pull/2226#issuecomment-297910593 an implementation was suggested that did just that - created dependencies so the updates happen in an efficient way, and the implementation was rather simple.

I checked how that implementation would hold up with OP's sample: using OP's fiddle, replacing https://rawgit.com/knockout/knockout/v3.5.0-rc2/dist/knockout.debug.js with the implementation suggested in https://github.com/knockout/knockout/pull/2226#issuecomment-297910593 causes the hide operation to complete with no noticable delay, see http://jsfiddle.net/fastfasterfastest/vdkn7ftj/39/.
Even a recusion depth of up to 500 causes the hide operation to be quick using that implementation, see http://jsfiddle.net/fastfasterfastest/vdkn7ftj/40/

> But while thinking about this again, I'm comfortable with a solution that only support deferred updates. That allows us to easily deal with binding updates separately from observable updates.

In general, I think it is a good idea and important to have same behavior whether deferred updates are in effect, or not.  I am not convinced a separate mechanism is needed for binding updates - if they can be handled by relying on observables and carefully creating dependencies (as my fiddles seem to indicate is possible) then I think that would be better.

**Comment by mbest** [comment] 2018-10-06 05:29
>In general, I think it is a good idea and important to have same behavior whether deferred updates are in effect, or not.

Makes sense. Thanks for putting together a concise example. I'll take a closer look at your approach and test it out.

**Comment by mbest** [comment] 2018-10-10 05:54
@fastfasterfastest Using your example, I've put together an update that should solve both problems. You can see the changes here: https://github.com/knockout/knockout/compare/2414-fastfasterfastest-if-dependency

@eapearson Please test this with your application and let me know how it goes. (http://bestware.us/knockout/2414-fastfasterfastest-update/)

**Comment by eapearson** [comment] 2018-10-11 15:50
@mbest will do starting today. Thanks to you both for the work on this.
I appreciate the need for consistent control flow and data flow behavior, and for the former not to be usurped by the latter, whether asynchronous behavior has been enabled or not.

**Comment by mbest** [comment] 2018-10-15 17:30
@eapearson Any update?

**Comment by eapearson** [comment] 2018-10-15 18:00
Sorry, was out sick most of last week. It is going fine so far, in that I have noticed nor have any issues been reported to me. Have a meeting in a few minutes, so can't look now -- is window.scheduled still populated? I remember from my flu-haze last week that it seemed to be absent.

**Closed** 2019-02-19 04:50 UTC
Labels: affected: few, severity: major, type: bug
