### ISSUE TITLE
I have a question about "if"

### ISSUE THREAD

**Issue by woshiwenzhijie** [knockout/knockout#1693] opened 2015-02-09 07:08 UTC
this is my jsfiddle url.
http://jsfiddle.net/3cdv3auw/

**Comment by nmehlei** [comment] 2015-02-09 09:37
Error 404, question not found

But apart from that, I think it would be better to post this to StackOverflow.

**Comment by brianmhunt** [comment] 2015-02-09 13:54
I agree with @nmehlei – @woshiwenzhijie you'll probably get a faster and better response on StackOverflow.

I will close this issue on that basis. However if the issue is with Knockout, please do re-open with details of the issue.

Cheers

**Closed by brianmhunt** 2015-02-09 13:54 UTC
