### ISSUE TITLE
ko.toJS creates undesired dependencies when called inside a computed observable

### ISSUE THREAD

**Issue by milanogc** [knockout/knockout#1705] opened 2015-02-25 11:15 UTC
Calling ko.toJS inside a computed observable creates undesired dependencies with the observables of the provided object.

The fix is to simple change `valueToMap = valueToMap()` by `valueToMap = valueToMap.peek()`, or make it an option of ko.toJS.

Sample: http://jsfiddle.net/dL4or8vh/

**Comment by brianmhunt** [comment] 2015-02-25 11:22
Hi @milanogc -- Thanks for the report. Using `.peek` is definitely one option. You can also wrap your call in `ko.ignoreDependencies(this.myAfterUpdateHandler, this, [true]);` in KO 3.3+ -- see http://www.knockmeout.net/2015/02/knockout-3-3-released.html

As `ko.toJS` automatically creates dependencies by design, and there are the two methods for turning off that dependency detection (`peek` and `ignoreDependencies`), so I will close this issue on that basis. But please let me know if I have missed or misunderstood something and we can re-open.

Cheers

**Closed by brianmhunt** 2015-02-25 11:22 UTC

**Comment by milanogc** [comment] 2015-02-25 12:09
Hi, @brianmhunt!
ko.ignoreDependencies solved the issue!
Thank you!

**Comment by brianmhunt** [comment] 2015-02-25 14:02
Awesome - cheers.
