### ISSUE TITLE
reset button doesn't work.

### ISSUE THREAD

**Issue by Lukiya** [knockout/knockout#745] opened 2012-12-04 12:49 UTC
If you put a button with 'reset' type in a form, you can see all your inputs are cleared after you click it.

but knockout didn't observed those value changes.

**Comment by SteveSanderson** [comment] 2015-04-07 13:47
Closing as not a bug, but please reopen if you disagree.

**Closed by SteveSanderson** 2015-04-07 13:47 UTC
Labels: close

**Comment by ebeeson** [comment] 2015-04-09 18:40
I think it's important to address this clearly in the docs. I'm a fairly veteran knockout user, but this caught me by surprise, and my googling brought me to this issue (which suggests to me that if this is covered in the docs, it isn't prominent enough for google search).

I understand why it is this way, but the end result is that the DOM gets out of sync with the viewmodel, which *feels* very much like a failing of knockout. AFAIK, this is by far the easiest 'corner case' where knockout breaksdown.

On the one hand, my expectation is that the `value`/`textInput`/`checked`/etc bindings might automatically walk up the DOM looking for a parent `form` to which a `reset` handler could be added to trigger updating any writable observables.

On the other hand, if the user is already dealing with the reset event, that might be a lot of unexpected 'magic' to have happen automatically.

Either way, might this be a good place to add a utility function? Something like `ko.domHasMutated(element)` that walks down the DOM (starting at the given element) and updates any bound writable observables (as @rniemeyer suggested)?

**Comment by brianmhunt** [comment] 2015-04-09 19:47
Thanks for the feedback @ebeeson; Where do you think is the best spot in the docs?

Cheers

**Comment by ebeeson** [comment] 2015-04-09 19:52
Maybe as a 'limitation' on the pages for the relevant bindings? (at least `value`, `textInput`, `checked`, and `selectedOptions`)

**Comment by ebeeson** [comment] 2015-04-09 20:57
Something like:

**Note:** the native form `reset` event can cause this binding to get out of sync with the view model. If you need to support the `reset` event, you must manually update any bound observables.

**Comment by crtjr64** [comment] 2017-10-05 02:22
Guys not having this in the documentation and forcing me to learn this the hard way cost me 5 hours, because I kept chasing every little piece of code over and over again until I got to this forum... its 10pm and I should have been finished at 6pm... guys c'mon that's just lazy. Moreso, now I cannot utilize the the single command of reset to reset my form and must traverse the editable fields to reset them which increases my coding as a function of the size of the form... I'm besides myself about this... chasing bugs for hours that does not exist.

**Comment by chrisknoll** [comment] 2017-10-05 03:01
Sorry about your trouble with the reset button. To a certain extent, browsers should be notifying the dom changes when the reset happens so that ko can pick up on it.

In lieu of a native reset, you can always persist the state of your initial form in a json-serialized form and when the reset click (a normal button, not a reset button) you just re-hidrate your model based on the original data.

**Comment by chrisknoll** [comment] 2017-10-05 03:04
Also, I tried to google this issue and found this within 2 minutes:
https://stackoverflow.com/questions/15889491/input-type-reset-and-knockout
