### ISSUE TITLE
KnockoutJS - Not detecting the Checkbox has been selected

### ISSUE THREAD

**Issue by RobertBroley** [knockout/knockout#2391] opened 2018-06-06 13:09 UTC
So I have an issue with KnockoutJS. Basically, I have a form that allows you to add a Writer and an Unknown Writer. If you are a Writer then you can select the Right to Collect checkbox, that is working fine.

So its when you change the Writer from Unknown to a Known Writer and Select the Right to Collect Checkbox its not taking into account its been updated and the checkbox has been selected.

However if you select and Unknown Writer, then edit it to a Writer, then update it, an error message appears:

> At least one writer must have the right to collect. 

I have added my Code into a PasteBin as its too large:

https://pastebin.com/ek3jagFa

This is what I have the checkbox for Right to Collect:

    <td class="hidden-xs hidden-sm">
        <div class="checkbox-custom checkbox-primary text-center" id ="right-collect"tabindex="0" data-bind="css: { 'checkbox-disabled': $data.WriterUnknownIndicator() == true }">
            <input type="checkbox" data-bind="checked: $data.RightToCollect, attr: { id: 'rightToCollect_' + $index(), disabled: $data.WriterUnknownIndicator() == true }">
            <label data-bind="attr: { 'for': 'rightToCollect_' + $index() }"></label>
        </div>
    </td>

**Comment by fastfasterfastest** [comment] 2018-06-06 20:36
The `checked` binding has successfully been used on input elements by many people an applications.

> I have added my Code into a PasteBin as its too large

If you think there is a problem/bug in the knockout implementation of the `checked` binding you need to distill it down to a reasonably-sized sample that demonstrates the problem.  My suspicion is that when you do that you will find the problem is in your application.

That said, after a super-brief peek at your code I saw the following:
```
if (name == UnknownWriterText)
{
   // When the writer is unknown, we do not want the right to collect checkbox enabled.
   rightToCollectCheckbox.prop('disabled', true);
   rightToCollectCheckbox.parent().removeClass('checkbox-primary');
   rightToCollectCheckbox.parent().addClass('checkbox-disabled');
}
else
{
   rightToCollectCheckbox.prop('disabled', false);
   rightToCollectCheckbox.parent().removeClass('checkbox-disabled');
   rightToCollectCheckbox.parent().addClass('checkbox-primary');
}
```

This may be part of your problem.  In a knockout application you don't update DOM elements in code like that, but instead use bindings.

**Comment by RobertBroley** [comment] 2018-06-06 20:46
Right okay, I thought it may be easier if I was to paste the whole code and describe my issue, so its not using bindings, okay I will have a go at that, to see if I can get it working with binding. Would you be able to give me a brief example of how this would work?

**Comment by fastfasterfastest** [comment] 2018-06-06 20:53
You seem to already be using bindings for some properties and attributes of the checkbox.  So, same thing with `disabled` and css classes, etc.

[The "enable" binding](http://knockoutjs.com/documentation/enable-binding.html)
[The "disable" binding](http://knockoutjs.com/documentation/disable-binding.html)
[The "css" binding](http://knockoutjs.com/documentation/css-binding.html)

I don't know if that's where your problem is, your code is just too large to analyze.

**Comment by mbest** [comment] 2018-06-07 03:56
Since this is a support request and not a problem in Knockout, I'm going to close the issue. As @fastfasterfastest said, you should stick with Knockout bindings and not use direct DOM access. Also your code snippet includes a `disabled` binding, but the binding is actually `disable`.

**Closed by mbest** 2018-06-07 03:56 UTC

**Comment by RobertBroley** [comment] 2018-06-07 08:28
@mbest  Can you delete this issue please?
