### ISSUE TITLE
SELECT.remove(0) is not working with OPTGROUP in IE9 (with standard document mode)

### ISSUE THREAD

**Issue by twpica** [knockout/knockout#785] opened 2013-01-02 04:17 UTC
I create an example here: http://jsfiddle.net/nhMBm/3/. You can play it around with IE9 (switch ducument mode to standard first).

In bindingHandlers `options`, 

```javascript
        // Remove all existing <option>s.
        // Need to use .remove() rather than .removeChild() for <option>s otherwise IE behaves oddly (https://github.com/SteveSanderson/knockout/issues/134)
        while (element.length > 0) {
            ko.cleanNode(element.options[0]);
            element.remove(0);
        }
```

when trying to remove `OPTION` under `OPTGROUP` by `remove()` method, 

```html
<select id="sel1">
  <option>Apple</option>
  <optgroup label="A">
    <option>Pear</option>
  </optgroup>
  <option>Banana</option>
  <option>Orange</option>
</select>
```
it will raise an error like this:

```
SCRIPT5022: DOM Exception: NOT_FOUND_ERR (8) 
```

According to #134 the method `removeChild()` is out of options. Does anyone know how to fix this?

**Comment by SteveSanderson** [comment] 2015-04-07 13:36
Thanks for posting. I'll close this now as it appears to be all working as intended (as @jrsearles mentions, optgroup isn't in scope for that binding), but please reopen if you disagree.

**Closed by SteveSanderson** 2015-04-07 13:36 UTC
Labels: waiting
