### ISSUE TITLE
Observable in expression for component binding

### ISSUE THREAD

**Issue by StrahilKazlachev** [knockout/knockout#1590] opened 2014-10-27 13:01 UTC
I have a VM with an observable property subVM. I want to pass a property which is an observable from the subVM in a component binding. I'm doing it like this  <some-component params="observableProp: VM.subVM().observableProp" .... Since I'm not evaluating the "observableProp" I was expecting the get an observable in the component. What I get is a computed with only a read accessor, which does return the correct value stored in the observable - here is a simple [fiddle](http://jsfiddle.net/s_kazlachev/gnfhh2fz/3/) just change the value and an error is thrown), but this way the value can not be modified. Is this the expected behaviour?

**Comment by jods4** [comment] 2015-01-19 21:36
I was reading the piece of code responsible for that today and I have to say it didn't feel very good or intuitive. :(

As reported here, why does `$raw` return the wrapping computed and not the underlying value directly? I can't see a benefit, but if it didn't: 
1. @StrahilKazlachev  could do `$raw.observableProp()`, as he expects.
2. With a suggestion I'm about to make in #1557 you could even write back values into the params!

Inside the same code, it also seems to me that the computed that are returned inside the params have excessive nesting? We have an accessor function, wrapped into a read-only computed, wrapped into a read-write computed. Is the middle layer really necessary? Moreover, if it was removed, the writable computed could handle writes back to a plain property and not just observables (again related to #1557).

Reference: https://github.com/knockout/knockout/blob/master/src/components/customElements.js#L55

**Comment by SteveSanderson** [comment] 2015-04-06 18:10
I know the double-dereferencing `someProp()()` in conjunction with `.raw` is pretty unpleasant, but in this edge case I'm not sure what better thing we can do. The existing API tries to make things as natural as possible for the more common cases, with the unfortunate cost that in unusual cases it becomes somewhat awkward.

It might work out more nicely if you don't put the complex expression directly inline in your view, but instead represent this as a computed on your host viewmodel.

I'll close this because it's as designed and I'm not sure that a better design is being proposed (though please clarify if so!).

**Closed by SteveSanderson** 2015-04-06 18:10 UTC

**Comment by mbest** [comment] 2015-04-06 19:11
> this way the value can not be modified.

With 3.3.0, the computed passed to the component will also be writable, so there's usually no need to use `$raw`.
