### ISSUE TITLE
Strange issue with ko.extenders and ko if binding

### ISSUE THREAD

**Issue by milaan-muc** [knockout/knockout#1830] opened 2015-07-21 08:52 UTC
Hi,

im trying to use extenders to give each observable a value to check if the observable is currently being edited. This is actually working very well until the the observable has no value anymore (empty or null). When this happens, my if binding cannot check the observable anymore.

```
ko.extenders.inlineEdit = function(target, options) {
  target.editing = ko.observable(false);
  target.edit = function() {
    target.edit(true);
  };
  target.subscribe(function(newValue) {
    if ( ! newValue) {
      target(null);
      target.editing(false);	
    } else {
      target.editing(false);
    }
  });
  return target;
}
```

```
<!-- ko if: port.editing -->
<input type="text" data-bind="value: port">
<!-- /ko -->
<!-- ko ifnot: port.editing -->
<div data-bind="click: port.edit"><span data-bind="text: port"></span></div>
<!-- /ko -->
```

As long as the observable has a value (for example 5), the div which shows the current value is visible. The i can click it to replace the div with the input field to change the value. When i change it to 6 and hit enter, the observable changes successfully and replaces the input field with the div again.
But when i remove any value from the input field (or when the initial value is empty), knockout is not showing a div or input field.

**Comment by mbest** [comment] 2015-07-21 09:03
Did you copy/paste this code or type it into GitHub? Because this doesn't seem like it will even do what you describe. For example:

```
    if ( ! newValue) {
      target(null);
      target.editing(false);    
    } else {
      target.edit(false);
    }
```

In the first case you're setting the observable `editing` to `false`, but in the second, you're calling the function `edit` instead.

**Comment by milaan-muc** [comment] 2015-07-21 09:39
Oh sorry typo. Corrected it above. target.edit(false) should be target.editing(false). The subscribe function is only there to remove the input field from the DOM and set a null value when empty.

My key problem is the the if binding is simply not working but there is also no error in the browser console. Somehow strange. Maybe i misunderstand something ....

**Comment by milaan-muc** [comment] 2015-07-21 13:00
Looks somehow that when port() is empty. That port.editing() is also not returning any result. Is that possible?

**Comment by brianmhunt** [comment] 2015-07-21 13:19
@milaan-muc This appears to be a support question and not an issue with KO *per se* (but please let me know if you think I am mistaken about that) – so I'll close this issue – but that said we can still try and help! :grin: It would be particularly helpful if you could please post a jsFiddle.

**Closed by brianmhunt** 2015-07-21 13:19 UTC

**Comment by milaan-muc** [comment] 2015-07-21 13:39
Well that my point... im not sure if this might be a bug or not or maybe an unexpected behavior. I will prepare a jsFiddle.

**Comment by brianmhunt** [comment] 2015-07-21 14:29
Thanks @milaan-muc – The expected behaviour is a very common pattern, so it is unlikely to be a bug. But you never know. :grin:

**Comment by mbest** [comment] 2015-07-21 19:44
There's no bug. When `port` is `null`, the `<span>` will just be empty and so won't display anything. You must use some other technique to ensure there's something to display and click when the value is empty. Here's a jsFiddle example: http://jsfiddle.net/mbest/37nygeoL/

**Comment by milaan-muc** [comment] 2015-07-22 10:56
I've made a fiddle too:
https://jsfiddle.net/Milaan/ty3hm0kv/7/

**Comment by milaan-muc** [comment] 2015-07-22 10:57
Oh my ... is it that simple? Didnt think about that :(
Thanks alot guys. Guess we can close this :)

**Comment by brianmhunt** [comment] 2015-07-22 11:51
@milaan-muc :grin: Done!
