### ISSUE TITLE
"with" property in "template" binding

### ISSUE THREAD

**Issue by miellaby** [knockout/knockout#2308] opened 2017-10-11 15:58 UTC
It's a feature request.

I often replace "with" bindings by "template" bindings because I need for its afterRender feature.

But in order to emulate the "with" binding behavior (which prevents falsy data to being rendered), I have to duplicate "if" and "data" properties in these "with"-equivalent "template" bindings.

So any chance for a "with" property in the "template" binding?

**Comment by brianmhunt** [comment] 2017-10-11 16:15
Is this a dupe of #2307?

How is the feature different from `template: { $data: thing, if: thing }`?

**Closed** 2017-10-11 18:37 UTC

**Comment by miellaby** [comment] 2017-10-12 07:02
@brianmhunt 

What if `thing` is a complex Javascript expression, or has a high computation cost? Yes I'm supposed to _always_ put computed observables in my model. But sometimes, it feels wrong doing so (a long debate I guess).

By the way, yes it's an involuntary duplicate. It looks like I've been tricked by some eventual consistency mechanism in github.

**Comment by brianmhunt** [comment] 2017-10-24 14:02
@miellaby The canonical way to handle high-computation items is to cache/memoize the result.

This is generally better than modifying the API to solve this problem.

One knockout-specific option is to have a filter (in punches or tko) that memoizes e.g. `thing|memoize:buster`, where `buster` is what breaks the memoization cache i.e.

```javascript
let memoized = new WeakMap()
ko.filters.memoize = function (fn, buster) {
  const key = ko.unwrap(buster)
  if (!memoized.has(key)) {
    memoized.set(key, fn())
  }
  return memoized.get(key)
}
```

Always open to other possibilities, too.
