### ISSUE TITLE
virtual elements broken in chrome

### ISSUE THREAD

**Issue by frankabbruzzese** [knockout/knockout#1759] opened 2015-04-09 16:15 UTC
When a virtual element is inserted after a `<table>` tag its closing tag appears misplaced. In fact chrome adds a tbody tag that overlaps just after the opening comment, but closes the tbody after the closing comment. Thus, the closing comment is lost withing the tbody.

I imagine that there is no feasible solution to this issue, but it should be mentioned in the documentation at least

**Comment by brianmhunt** [comment] 2015-04-09 16:19
@frankabbruzzese Thanks for the report.

It seems like some of your markup was clobbered, so I cannot tell what the issue is. It may help if you wrap your example in <code>```</code>

Cheers

**Comment by frankabbruzzese** [comment] 2015-04-10 09:14
Put the following code into an html page, and open it with chrome:
```
<!DOCTYPE html>
<html>
<head> 
</head>
<body>
<table  data-bind="foreach: Matrix">
<!-- ko enableParsing: true, validation: true -->
	<tr  data-bind="foreach: $data">
	<!-- ko enableParsing: true, validation: true -->
            <td>
               <span data-bind="text: Name" ></span> 
            </td>
        <!-- /ko -->
	</tr>
<!-- /ko -->
</table>
</body>
</html>
```
You don't need to include knockout, or to redefine my custom binding, since the problem is the browser adding a tbody tag that breaks the the outermost "enableParsing" virtual element.

If you select " inspect element" in the right click menu you can see how the browser rewtite the above markup:
![commentbreaking](https://cloud.githubusercontent.com/assets/614976/7084884/f82d5ed0-df71-11e4-916d-e2b526bd9ef8.PNG)

As you can see while the opening tag is left out of the tbody the closing tag is put inside the <tbody>.
This depends of the browser ignoring the semantict of ko comments. Similar errors may occur each time a browser insert automatically a tag. So I suppose the problem appears also in other browser and in other circumnstances.

There is no general solution...other than avoiding virtual elements. Luckily, in each case the code may be fixed by adding manually the tag automatically inserted by the browser,...but in the proper way :)

I think, the above problem should be mentioned in the documentation of virtual elements, together with the way to fix it...otherwise people might go crazy when a similar error occurs.

**Comment by IanYates** [comment] 2015-04-10 11:31
:+1: for getting this into the docs - if it helps save a newbie some hair-pulling time then it's worth it.  
Aside: I remember running into this sort of problem when I started trying the punches library...  Browsers just completely eat plain text like {{if: xyz}} in places like <table> tags.

**Comment by brianmhunt** [comment] 2015-04-10 12:14
@frankabbruzzese What happens if you change the code to this:

```html
<table >
  <tbody data-bind="foreach: Matrix">
<!-- ko enableParsing: true, validation: true -->
    <tr  data-bind="foreach: $data">
    <!-- ko enableParsing: true, validation: true -->
            <td>
               <span data-bind="text: Name" ></span> 
            </td>
        <!-- /ko -->
    </tr>
<!-- /ko -->
  </tbody>
</table>
```

I suspect the problem is that the `<tbody>` tag is auto-inserted, per the HTML spec, which hoists the comments out.

Agree that it should be in the docs.

Appreciate if you could let me know though if adding an explicit `<tbody>` helps.

Cheers

**Comment by frankabbruzzese** [comment] 2015-04-10 12:23
@brianmhunt ,
Of cousse adding manually the tbody tag solves. Thus, this issue can always be solved by adding the browser added tag. The only point, in my opinion is just mentioning in the docs that  when getting an unbalanced virtual element error message, one should verify if the break was caused by the browser adding an extra tag.

**Comment by brianmhunt** [comment] 2015-04-10 12:36
@frankabbruzzese – Got it, thanks!

**Comment by SergioMorchon** [comment] 2015-04-16 09:13
I think it is like talking about hoisting var in JavaScript. It's not knockout or browser specific, but language specificacion. +1 @brianmhunt

**Comment by brianmhunt** [comment] 2015-07-14 18:23
I have put a note into the docs on the [new alpha website](http://brianmhunt.github.io/knockout/a/custom-bindings-for-virtual-elements.html); closing this but please let me know if I have missed something or there's an improvement possible here.

Cheers

**Closed by brianmhunt** 2015-07-14 18:23 UTC
Labels: affected: few, severity: minor, type: bug
