### ISSUE TITLE
ko.utils.domData.nextKey has wrong name in minified version

### ISSUE THREAD

**Issue by Uncaught-Exception** [knockout/knockout#1819] opened 2015-06-29 11:28 UTC
The method `ko.utils.domData.nextKey` is called `ko.utils.domData.I` in the minified version.

I don't know if this is intentional or a bug in the minifying process or the method should actually be private and not accessible. All other methods (get, set, clear) in `ko.utils.domData` have the correct original name.
I need the method for my own template binding handler and are stuck with this workaround for now:
```var templateComputedDomDataKey = ko.utils.domData.nextKey ? ko.utils.domData.nextKey() : ko.utils.domData.I();```

**Comment by brianmhunt** [comment] 2015-06-29 14:21
@Uncaught-Exception Thanks for the report. This is not a bug but a minification issue. Right now I am sorry to report that `nextKey` is not an exported part of the KO package.

This will be fixed (or at least addressed) in #1369, and so I am closing this.

The only alternative in the interim would be to use the debug version of Knockout (which you can minify with *uglify* to save space but not lose the unexported `nextKey` symbol).

Sorry the answer is not better for the moment, but I hope this helps.

**Closed by brianmhunt** 2015-06-29 14:21 UTC

**Comment by Uncaught-Exception** [comment] 2015-06-29 14:35
Thank you! I will wait for the fix then and keep my work around in place for the time being.

**Comment by mbest** [comment] 2015-06-29 22:51
The minified name can and probably will change with a new release. It's not necessary to use `ko.utils.domData.nextKey` because you can use any string you want for `ko.utils.domData`.
