### ISSUE TITLE
Component params/componentInfo should include outer context

### ISSUE THREAD

**Issue by joeheyming** [knockout/knockout#1851] opened 2015-08-14 17:04 UTC
When I create a new Component:

var MySweetComponent = function(params, componentInfo) {
// ...
}
ko.components.register('mysweetcomponent', { viewModel: {
createViewModel: function(params, componentInfo) {
return new MySweetComponent(params, componentInfo);
}, template: myTemplate});

I don't have access to the component context, unless I do something like this:
&lt;mysweetcomponent params="context: $context"&gt;
&lt;!-- ... --&gt;
&lt;/mysweetcomponent&gt;

But if we implicitly included the context, then we could access it like this:
componentInfo.$context.thing_I_really_Need

What do you think?

**Comment by mbest** [comment] 2015-08-14 18:42
Duplicate of #1666

**Closed by mbest** 2015-08-14 18:42 UTC

**Comment by joeheyming** [comment] 2015-08-14 19:33
You guys rock!  ko.contextFor is *exactly* what I wanted
