### ISSUE TITLE
submit onenter binding not reevaluated if same value

### ISSUE THREAD

**Issue by ivRegiS** [knockout/knockout#2206] opened 2017-02-16 18:35 UTC
not leaving the input and submitting twice the same value using "enter" do not works.
https://jsfiddle.net/ocg90j0u/

I use chrome

**Comment by mbest** [comment] 2017-02-16 19:37
I followed your instructions and did not see any problem. I'm using Chrome 55.0.2883.87 64-bit on Windows.

**Comment by angelpcadena** [comment] 2017-02-22 23:40
I can reproduce this issue.

Chrome 56.0.2924.87 64-bit Win10

![input](https://cloud.githubusercontent.com/assets/938243/23238100/fdaf5ce4-f925-11e6-89fa-c3d72d3111b3.gif)

**Comment by mbest** [comment] 2017-02-23 03:06
It must be a bug in the new version of Chrome.

**Comment by chrisknoll** [comment] 2017-02-23 04:46
That's strange, I was not able to reproduce this when it was originally posted, but now if you submit the same value twice you get null.

**Comment by chrisknoll** [comment] 2017-02-23 04:48
Btw, it doesn't have to just be via enter key, clicking submit button with the same value 20 causes the null to appear. Also, interestingly, if you hit submit,t he field clears out but in one case I coudl get it that typing in the prior value and then clicking submit did not clear the form field, and the value reported was null.  So definitely some wierd behavior with submit buttons.

**Comment by chrisknoll** [comment] 2017-02-23 04:51
Ok, yes i reproduced it:

Type in 20, hit enter -> form field clears
type in 20, click submit -> form field does not clear, null value logged
keep hitting enter, null value reported.

**Comment by mbest** [comment] 2017-02-23 06:52
So updated my Google Chrome, and now I see the problem. Before it worked just fine.

**Comment by mbest** [comment] 2017-02-23 07:04
I've reported this to Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=695349

But the issue was marked as spam, so please help get this noticed.

**Comment by angelpcadena** [comment] 2017-02-23 15:50
@mbest  I used [Screed2Gif](https://screentogif.codeplex.com/)

**Comment by chrisknoll** [comment] 2017-02-23 16:41
Hey, @mbest, i tried to go to the link but when i go to the page, it gives me a dialog box which I can't dismiss so i can't go in and vote for it :( maybe another chrome bug :(  but I'll keep an eye on it.  I was able to log in tho, it just keeps giving me this dialog about the email settings.

**Comment by mbest** [comment] 2017-02-23 17:22
Someone commented on my Chrome bug pointed to https://crrev.com/430531

**Comment by codymullins** [comment] 2017-02-25 20:38
Looks like they have the fix for this already and should be out in the next week or so's beta release

**Comment by mbest** [comment] 2017-03-01 19:44
The Chrome bug will be fixed in version 57.

**Closed by mbest** 2017-03-01 19:44 UTC
