### ISSUE TITLE
TableSorter wit kncokout and computed ArrayObservable

### ISSUE THREAD

**Issue by biocar2001** [knockout/knockout#1791] opened 2015-05-13 15:13 UTC
Hi,

We have a table which one show the users with the help of jquery plugin table. When We are using this control with knockout and we iterate the table with a observable Array everything is fine with the help of a handler developed for us:

```javascript
ko.bindingHandlers.sortTable = {
        init: function(element, valueAccessor) {
            var iden=$(element).attr("id");
            setTimeout( function() {
                if($(element).hasClass('tablesorter')){
                    ko.utils.unwrapObservable(valueAccessor())
                    $(element).trigger('updateAll');
                }else{
                    $(element).tablesorter({
                        widgetOptions:{filter_external : '#'+iden+"_search"}
                        //headers: {0: {sorter: false}}
                    }).tablesorterPager({container: $('#'+iden+"_pager")});
                }
            }, 0);
        },
		update: function(element, valueAccessor) {
	       $(element).trigger("update");
        }
    };

```
and in the template we do binding in this way:

```html
<tbody data-bind="foreach: MyListObservable">
```

The problem happen when our MyListObservable is a computed value, which one is recalculated in function of other check observable. In this case the behaviour of the control is strange and always add elements to the table but when the observable array remove information this one dont update the index of the table and theirs values. I have tried without success:

1º RemoveAll the values of the array before reload the array.
2º Force the updateAll the table just after of reload of computed value $(element).trigger('updateAll').
3º Get the value of the computed and assign his value to other observable array and iterate with this new array.

I know here is the repository of knockout and not of tableSorter.jquery but obviously the problem has relation with knockout and maybe other users had the same problem.
Any idea?
Thanks in advance.

**Comment by brianmhunt** [comment] 2015-05-13 15:49
Thanks for the report @biocar2001 – As a support request, and not an issue with Knockout per se, I am going to suggest you try posting your question on Stackoverflow or [gitter.im](https://gitter.im/knockout/knockout), and close this issue (as the Github repo is for issues with Knockout itself, and not support *per se*). You can continue to discuss this question here, and please let me know if I am mistaken in thinking there is nothing wrong with Knockout here, and we will reopen!

That said, I think the issue you *may* be encountering is that the basic array functions like `sort`, `indexOf`, etc., are not included on the computed.

One option may be, if you are able, to have `observableArray` copy set up like this:

```javascript
computed = ko.computed(...)
arr = ko.observableArray()
computed.subscribe(arr)
```

The obvious upside is that if you bind against `arr` it'll work as it had before. The downside is the memory usage and performance impact of copying the array from the computed every time there is a change (though you can mitigate this latter problem somewhat by throttling). If the performance and memory are not concerns, this may be the way to go.

I hope that helps, and as mentioned please do not hesitate to continue discussing this issue here - even though the issue is closed we may still be able to help. :smile:

Cheers

**Closed by brianmhunt** 2015-05-13 15:49 UTC

**Comment by biocar2001** [comment] 2015-05-14 10:40
thanks by your answer, I tried your suggestion but is wrong :-(, I'm sorry for the question in your repository, but I wrote this post in stackoverflow too and anyone know what is the problem:

http://stackoverflow.com/questions/30218970/table-with-tablesorter-in-knockout-with-computed-value-for-iteration.

Thanks.

**Comment by brianmhunt** [comment] 2015-05-14 12:16
Thanks for the update @biocar2001 ...

Since the error seems non-trivial your best bet might be to create a jsFiddle or jsBin that demonstrates the problem and post that here and on SO.

Cheers
