### ISSUE TITLE
afterRender callback for if binding

### ISSUE THREAD

**Issue by martinstein** [knockout/knockout#421] opened 2012-04-03 14:08 UTC
The `foreach` and `template` binding both offer `afterRender` callbacks. Currently, that callback is not present for the standard `if` binding. I solved the problem by using a template-binding within my `if` code, so there would be an afterRender option. But this seems hacky!

tl;dr: An `afterRender` callback for `if` would be really nice (and it would make `if` more consistent with `foreach` and `template`).

**Comment by SteveSanderson** [comment] 2015-04-08 12:16
Closing as duplicate of #1529 (I know this one was posted first, but the other one has more discussion and is wider-scoped).

**Closed by SteveSanderson** 2015-04-08 12:16 UTC
