### ISSUE TITLE
textInput binding doesn't update observable when using ESC key to reset the input on IE10 and IE11

### ISSUE THREAD

**Issue by jbaez** [knockout/knockout#2232] opened 2017-04-27 10:00 UTC
Using a text field like:
`<input type="text" data-bind="textInput: anObservable" /> `
To reproduce:
- Type something in the input field and press Enter key
- Select all the text in the input field and replace by something else
- Press ESC key to reset to the previous value
- The observable won't be updated after it has been reset to the previous value (not even after pressing Enter key)

When using value binding + valueUpdate: 'afterkeydown' it works fine.

There is a bug with IE not firing Input events: https://connect.microsoft.com/IE/feedback/details/881670/ie11-esc-key-changes-value-of-input-type-text-but-does-not-fire-input-event

I tried to take a look at the textInput binding code to subscribe to keydown only in IE10 and IE11 but ko.utils.ieVersion is undefined

**Comment by mbest** [comment] 2017-10-03 03:37
Duplicate of #1678. Fixed with 11e3cb93671b69b0fb26239ad4f2d2f75d6c6cc3

**Closed by mbest** 2017-10-03 03:37 UTC
Labels: affected: average, severity: minor, type: bug
