### ISSUE TITLE
"You cannot apply bindings multiple times to the same element" during traversing a DOM tree after applyBindings

### ISSUE THREAD

**Issue by San4es** [knockout/knockout#1053] opened 2013-07-29 13:29 UTC
I have сustom binding handler 'overlay', which moves content into another container during the processing (see http://jsfiddle.net/San4es/ESCT4/). After calling ko.applyBindings, I get the exception: "You cannot apply bindings multiple times to the same element". I understand that the problem is related to a modification of the DOM tree during traversing by Knockout.

How can I avoid this issue? Is the problem the expected?

Thanks,
Alexander.

**Comment by SteveSanderson** [comment] 2015-04-07 12:59
I'll close this as it's by design (and so old that it's unlikely still to be an active concern). Please reopen if anyone disagrees!

**Closed by SteveSanderson** 2015-04-07 12:59 UTC
